version: "3"

services:
  api:
    image: fedemarkoo/meliproxyapi
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-replica:
    image: fedemarkoo/meliproxyapi
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-replica-2:
    image: fedemarkoo/meliproxyapi
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  manager:
    image: fedemarkoo/meliproxymanager
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"