version: "3"

services:
  api:
    image: fedemarkoo/meliproxyapi
    ports:
      - "81:8080"
    environment:
      SPRING_PROFILES_ACTIVE: aws

  manager:
    image: fedemarkoo/meliproxymanager
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: aws

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"