services:
  api:
    build: MeLi-Proxy-Api/.
    ports:
      - "80:80"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker



  redis:
    image: redis
    container_name: redis
  mongo:
    image: mongo
    container_name: mongo