version: "3"

services:
  api:
    build: MeLi-Proxy-Api/.
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  manager:
    build: MeLi-Proxy-Manager/.
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  redis:
    image: redis
    container_name: redis
  mongo:
    image: mongo
    container_name: mongo