version: "3.9"  # optional since v1.27.0
services:
  api:
    build: MeLi-Proxy-Api/.
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

  manager:
    build: MeLi-Proxy-Manager/.
    ports:
      - "8081:8080"
    depends_on:
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017