springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger-ui.html

com.meli.fede.markoo:
  proxy:
    baseurl: api.mercadolibre.com
    maxvalues:
      maxRequestPerCombo: 20
      maxRequestPerPath: 20
      maxRequestPerIp: 20

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    discovery:
      enabled: true
  cache:
    redis:
      time-to-live: 5