springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger-ui.html

spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    view:
      prefix: /
      suffix: .jsp
  data:
    mongodb:
      database: MeLi-Proxy

server:
  port: 8081