springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger-ui.html

spring:
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: MeLi-Proxy

server:
  port: 8081