name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./MeLi-Proxy/MeLi-Proxy-Api --file MeLi-Proxy/MeLi-Proxy-Api/Dockerfile --tag meli-proxy:$(date +%s)
