
name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  publish-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 8
        - run: mvn -B package --file pom.xml -DskipTests
        - run: mkdir staging && cp MeLi-Proxy-Api/target/*.jar staging
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
  
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [publish-job]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u fedemarkoo -p asd123qwe
      - name: Build Container image
        run: docker build -t meliproxyrepo:latest .
      - name: Publish Docker image
        run: docker push meliproxyrepo
