
name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:   
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest ./MeLi-Proxy-Api
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}/meliproxyapi
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest ./MeLi-Proxy-Manager
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}/meliproxymanager
